export {default as LoginPage} from '../pages/LoginPage'
export {default as SignUpPage} from '../pages/SignUpPage'
export {default as Home} from '../pages/Home'
export {default as AddressForm} from '../pages/AddressForm'
export {default as AddressList} from '../pages/AddressList'
export {default as AddressUpdateForm} from '../pages/AddressUpdateForm'
export {default as StockList} from '../pages/StockList'
export {default as StockForm} from '../pages/StockForm'
export {default as StockUpdateForm} from'../pages/StockUpdateForm'
export {default as StockSearch} from '../pages/StockSearch'